services:
  - type: web
    name: ecuacionesaword
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn_conf.py main:app"
    healthCheckPath: /healthz
    envVars:
      - key: WEB_CONCURRENCY
        value: 2
      - key: PYTHON_VERSION
        value: 3.11.14
      - key: ENVIRONMENT
        value: production
